version: "3.8"

services:
    backend:
        build: ./backend

        ports:
            - "5000:5000"
        volumes:
            - ./backend/src:/api/src

    frontend:
        build: ./frontend

        ports:
            - "3000:3000"

        volumes:
            - ./frontend/src:/client/src
        # allow interactive mode
        stdin_open: true
        tty: true

        depends_on:
            - backend

# declare the volumes name that our app is using.
volumes:
    data:
